build:
	odin build . -out:../build/Renderer.exe -debug -show-timings -terse-errors -o:none

build-speed:
	odin build . -out:../build/Renderer.exe -show-timings -o:speed

build-aggressive:
	odin build . -out:../build/Renderer.exe -show-timings -o:aggressive

run:
	odin run . -out:../build/Renderer.exe -debug -show-timings -terse-errors -o:none

clean:
	rm ./build/Renderer
